### ISSUE TITLE
[Suggestion] Few Ideas from me ;)

### ISSUE THREAD

**Issue by Adis439** [dolutattoo/DoluMappingTool#12]
Hey!

- Add a `Miscs` tab with following:
  - [ ] Disable cops chasin you
  - [ ] Set default default ped on spawn
  - [ ] Set default weapons on spawn
  - [ ] Customize weapons

- [x] Add option to controle speed in noclip, make it that you can slower faster etc..

For now i got this! :) very nice tool I was usin it long way before this version, happy to see how it will go.

**Comment by tiwabs** [comment]
For the noclip you already have control to move slower or faster, you can press Shift to move faster.
You can also use Scroll to adjust your movement speed. Scroll up decrease your speed, Scroll down increase your speed
All options for noclip are at the bottom right of your screen
![image](https://user-images.githubusercontent.com/48737497/214957424-b31d9467-1e6c-42cd-b3b1-cd47138854fc.png)

**Comment by Adis439** [comment]
> For the noclip you already have control to move slower or faster, you can press Shift to move faster. You can also use Scroll to adjust your movement speed. Scroll up decrease your speed, Scroll down increase your speed All options for noclip are at the bottom right of your screen ![image](https://user-images.githubusercontent.com/48737497/214957424-b31d9467-1e6c-42cd-b3b1-cd47138854fc.png)

Damn I haven't notice scroll adjustment 😄

**Comment by DoluTattoo** [comment]
Setting default ped/weapons require some checks for framework/inventory resources but could be cool, yes.
Should definitely be disabled by default tho
