### ISSUE TITLE
Quality of life improvement

### ISSUE THREAD

**Issue by krzysiula3000** [dolutattoo/DoluMappingTool#13]
Could you please make typing freeze keyboard actions? For example when i want to spawn a prop by name i accidentally open half my menus, like vMenu etc. Again, not really a bug, but it's insanely frustrating

**Comment by DoluTattoo** [comment]
Tell me which keys are causing issues and I'll add them to next release

**Comment by krzysiula3000** [comment]
Basically the whole keyboard m, v, l, f, t, p, q etc. etc.

**Comment by DoluTattoo** [comment]
Done
