### ISSUE TITLE
Disappearing text

### ISSUE THREAD

**Issue by krzysiula3000** [dolutattoo/DoluMappingTool#14]
I downloaded ox_lib as well as ox_target, set up everything according to the documentations, however when using 4.2.0 version of the tool, the text just disappears whenever i load into the game, in order to see it again i have to restart the resource
![image](https://user-images.githubusercontent.com/95538762/215542570-21a123ef-16d6-413c-8075-6c5099ad883d.png)

**Comment by DoluTattoo** [comment]
Are you using vMenu ?
If yes try to disable it and run your server again.
Some people are experiencing the exact same thing and it solve the issue.

If anyone have an idea what could cause conflict about this.. you're welcome!

**Comment by krzysiula3000** [comment]
Yes I do, restarting the resource works just fine, so no need to disable vMenu, restarting it gets kinda annoying after some time though

**Comment by DoluTattoo** [comment]
Can you try what I said please?

**Comment by DoluTattoo** [comment]
Will continue this issue on #17
