### ISSUE TITLE
[Bug] A delay in the permission function causes the menu to break

### ISSUE THREAD

**Issue by edwardexo** [dolutattoo/DoluMappingTool#17]
**Describe the bug**
Currently, the permission system is client-side. However, some information which I want to use for permissions is kept server-side.

I created a simple server-side callback `dolu_tool:isAuthorized` which returns true or false. I'm trying to use this callback in the permission function, but the menu breaks when using it.

**To Reproduce**
1. Create a server-side callback:
```
lib.callback.register('dolu_tool:isAuthorized', function(source)
    return true
end)
```
2. Use the server-side callback in the permission system.
```
Config.perimission =  function(type)
    return lib.callback.await('dolu_tool:isAuthorized', false)
end
```
3. Try to open the mapping tool.
4. The opened mapping menu is bugged and there's an error in the F8 console: `Uncaught (in promise) SyntaxError: Unexpected end of JSON input (@dolu_tool/web/build/index.html:1)`.

**Expected behavior**
The menu should open correctly and not be bugged.

**Screenshots**
Screenshot of the error and you can see the menu is bugged (no text in the boxes).
![image](https://user-images.githubusercontent.com/118666903/218709345-50713ced-6ec9-42b6-9976-4e7d826db906.png)

**Additional context**
Seems that if you don't return the permission instantly, it breaks. You can also do `Wait(100)` before returning true/false and the same problem will happen.

I sometimes get the same error & bug totally randomly as well, without any changes to the script - similarly to https://github.com/dolutattoo/dolu_tool/issues/14 

It seems if something is not loaded quick enough, the F8 HTML error appears and the menu gets bugged.

**Comment by DoluTattoo** [comment]
Latest commit should fix this. If someone is able to build nui from source code and test
