### ISSUE TITLE
[Suggestion] Props finding

### ISSUE THREAD

**Issue by Kentainfr** [dolutattoo/DoluMappingTool#21]
**Is your feature request related to a problem? Please describe.**
Feature request since I don't find it on the menu. 

**Describe the solution you'd like**
Basically when we use dolu_tool there is no functions to find a props name. We can spawn some but not copy the name. So for example I'm currently in a MLO. I have an object I want to remove but I can't since I don't know the name. I use the menu to find the specific props. Once it's done the name is coppied to clipboard and then I can remove it easily. 

**Additional context**
It will allow mappings to get easily edited.

**Comment by Aik-10** [comment]
**I think this problem will be already solved in [master](/dolutattoo/dolu_tool/tree/master), u can select object by L click mouse, then u can copy model name.**

**Comment by DoluTattoo** [comment]
This will be available in next release, yes

**Comment by DoluTattoo** [comment]
Implemented in v4.3.0
