### ISSUE TITLE
[Bug] Script doesn't support interiors without portals

### ISSUE THREAD

**Issue by e-49** [dolutattoo/DoluMappingTool#24]
**Describe the bug**

**To Reproduce**
1. Go to any interior without portals (oneroom underground interior)
2. Open dolu tool UI
3. Click on interior tab
4. Get stuck with hidden ui
Screenshot: https://imgur.com/a/LrxW3J7

**Comment by ghost** [comment]
Every interior needs a portal, the entrance into the interior is a portal lol

**Comment by DoluTattoo** [comment]
> Every interior needs a portal, the entrance into the interior is a portal lol

No, you can do MLOs only accessible by teleport.
I need to find the time to fix it.
If someone read this do not hesitate to contribute

**Comment by DoluTattoo** [comment]
Fixed in 4.2.3
