### ISSUE TITLE
[Bug] Unexpected end of JSON

### ISSUE THREAD

**Issue by xXRexXx** [dolutattoo/DoluMappingTool#25]
**Describe the bug**
Im not sure if its a bug but I keep getting this error as below after a few times of restarting my server. 

"SyntaxError: Unexpected end of JSON input (@dolu_tool/web/build/index.html:1)"

![image](https://user-images.githubusercontent.com/41901333/230747797-c660319b-3437-4e69-9a94-3fd33c451a41.png)

For the first few times Im able to open the menu, after a few server restart, the error will show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/41901333/230747782-b6e70ffb-9aaf-4d15-9e11-e23963cd2efe.png)

**Comment by DoluTattoo** [comment]
I cant reproduce the bug so im not able to fix it
