### ISSUE TITLE
loading script causes major errors

### ISSUE THREAD

**Issue by Soldierofthelam** [dolutattoo/DoluMappingTool#26]
I've got ox-lib installed for other scripts and updated 
both scripts are ensured pressing f3 to call script produces these errors.

[    295875] [b2699_GTAProce]             MainThrd/ Error loading script server/main.lua in resource dolu_tool: @dolu_tool/server/main.lua:131: attempt to index a nil value (global 'Shared')
[    295875] [b2699_GTAProce]             MainThrd/ stack traceback:
[    295875] [b2699_GTAProce]             MainThrd/ 	@dolu_tool/server/main.lua:131: in main chunk
[    295875] [b2699_GTAProce]             MainThrd/ Failed to load script server/main.lua.
[    295875] [b2699_GTAProce]             MainThrd/ Started resource dolu_tool
[    295875] [b2699_GTAProce]             MainThrd/ 
[    295890] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Downloading content manifest...
[    295890] [b2699_GTAProce]  UV loop: httpClient/ Required resources: dolu_tool 
[    295921] [b2699_GTAProce]             MainThrd/ Creating script environments for dolu_tool
[    295921] [b2699_GTAProce]             MainThrd/ Error loading script client/commands.lua in resource dolu_tool: @dolu_tool/client/commands.lua:6: attempt to call a nil value (global 'locale')
[    295921] [b2699_GTAProce]             MainThrd/ stack traceback:
[    295921] [b2699_GTAProce]             MainThrd/ 	@dolu_tool/client/commands.lua:6: in main chunk
[    295921] [b2699_GTAProce]             MainThrd/ Failed to load script client/commands.lua.
[    295937] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/controls.lua:6: attempt to index a nil value (global 'Client')^7
[    295937] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/controls.lua^7:6)
[    295937] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/controls.lua:53: attempt to index a nil value (global 'Client')^7
[    295937] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/controls.lua^7:53)
[    295937] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/threads.lua:9: attempt to index a nil value (global 'Client')^7
[    295937] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/threads.lua^7:9)
[    295937] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/threads.lua:25: attempt to index a nil value (global 'Client')^7
[    295937] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/threads.lua^7:25)
[    295937] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/threads.lua:41: attempt to index a nil value (global 'Client')^7
[    295937] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/threads.lua^7:41)
[    295937] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/threads.lua:66: attempt to index a nil value (global 'Client')^7
[    295937] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/threads.lua^7:66)
[    295937] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/threads.lua:94: attempt to index a nil value (global 'Client')^7
[    295937] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/threads.lua^7:94)
[    295937] [b2699_GTAProce]             MainThrd/ OnConnectionProgress: Mounted dolu_tool (1 of 1)
[    296453] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @dolu_tool/client/threads.lua:3: attempt to index a nil value (global 'Client')^7
[    296453] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@dolu_tool/client/threads.lua^7:3)

**Comment by DoluTattoo** [comment]
What version of the tool do you use? Are you using release or source code ?

**Comment by Soldierofthelam** [comment]
I'm using the release script link on the right side not the drop down link for source 

I checked my cache files deleted everything fivem side and server side caches restarted the server same thing, then I tried a second restart thinking how some of my scripts require it and this seems to have worked restarting the server twice after ensuring files.

the first one on top
![Screenshot 2023-04-20 003541](https://user-images.githubusercontent.com/117047687/233259278-862909bc-a2a6-49d3-9ea7-c3522034a68c.png)

**Comment by DoluTattoo** [comment]
So it works now ?
When I check your logs it looks like the script cannot load ox_lib stuff.
Make sure to start ox_lib first and then dolu_tool

**Comment by Soldierofthelam** [comment]
> So it works now ? When I check your logs it looks like the script cannot load ox_lib stuff. Make sure to start ox_lib first and then dolu_tool

Yes it works now for some reason after first install it seems that the server required a second restart to function properly which is not uncommon with some scripts for first time installs
