### ISSUE TITLE
[Bug] Pool Size crash after install this script and noclip

### ISSUE THREAD

**Issue by Snipy44** [dolutattoo/DoluMappingTool#28]
Hi, after install and ue the script my game crash with pool size, i try the script with 0 mapping and the probleme persist. after no clip and move fast , the game crash.

![image](https://user-images.githubusercontent.com/3805333/233821925-f39d0e57-326a-4ef5-b49d-4d73708d4e2c.png)

**Comment by DoluTattoo** [comment]
This cannot be related to this ressource.
Try to use builtin client debugging tools to identify which pool size has been reach
