### ISSUE TITLE
[Suggestion] Rotation button

### ISSUE THREAD

**Issue by adweex** [dolutattoo/DoluMappingTool#30]
**Is your feature request related to a problem? Please describe.**
Would be greate a get rotation button right beside the position button.

**Comment by DoluTattoo** [comment]
What do you mean?

**Comment by necaz1337** [comment]
When u spawn an object usind dolu tool, u need to implement heading function to rotate the object like map editor

> What do you mean?

**Comment by necaz1337** [comment]
> 

SetEntityRotation

**Comment by adweex** [comment]
> What do you mean?

When you spawn an object you have the ability to copy the position of it to the clipboard. Would be great if you could copy the rotation of it.

**Comment by DoluTattoo** [comment]
Button was added in PR #31. Will be included in next release!
