### ISSUE TITLE
[Suggestion] Audio Emitter Feature

### ISSUE THREAD

**Issue by Sanriku-Gaming** [dolutattoo/DoluMappingTool#8]
**Is your feature request related to a problem? Please describe.**
Add audio emitter info for interiors in the area

**Describe the solution you'd like**
The ability to see audio emitters in the area

**Additional context**
As you mentioned here https://forum.cfx.re/t/dolu-tool-mlo-debugging-object-spawner-more/5000677/11?u=sanriku This is possible via dump, so adding the feature request as a reminder.

**Comment by DoluTattoo** [comment]
Done!
