### ISSUE TITLE
[Suggestion] Permission

### ISSUE THREAD

**Issue by PoorLatency** [dolutattoo/DoluMappingTool#9]
Add an option for only those with ace permissions can access tool.

**Comment by Sojobo** [comment]
It would be nice to expand on this and have separate permissions for different functions too, even if it's just as generic as permissions per tab or something.

**Comment by DoluTattoo** [comment]
@Sojobo I won't go more deep with permission system than what I have made in config file, because this is a dev tool and it should not run in prod environment , only in development servers.
